-- ============================================================
-- LÓGICAS PXG V3 — SUPABASE / POSTGRES
-- Execute este arquivo uma vez no SQL Editor do Supabase.
-- ============================================================

create extension if not exists pgcrypto;

-- PERFIS PÚBLICOS (as senhas ficam no Supabase Auth e NÃO nesta tabela)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 3 and 24),
  avatar_url text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

-- MATÉRIAS
create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null check (char_length(title) between 3 and 180),
  category text not null,
  author text not null default 'Redação Lógicas PXG',
  summary text not null check (char_length(summary) <= 360),
  content text not null,
  score smallint not null default 0 check (score between 0 and 100),
  icon text not null default '📰',
  cover text not null default 'dark' check (cover in ('red','yellow','blue','purple','green','dark')),
  cover_image_url text,
  featured boolean not null default false,
  published boolean not null default true,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- UMA REAÇÃO POR USUÁRIO EM CADA MATÉRIA (Curtir OU Amei)
create table if not exists public.reactions (
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reaction text not null check (reaction in ('like','love','funny')),
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

-- COMENTÁRIOS
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 800),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_username_unique_ci on public.profiles ((lower(trim(username))));
create index if not exists idx_posts_published_at on public.posts(published_at desc);
create index if not exists idx_comments_post_id on public.comments(post_id, created_at desc);
create index if not exists idx_reactions_post_id on public.reactions(post_id);

-- Cria o perfil público automaticamente quando uma conta nasce no Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    left(coalesce(nullif(trim(new.raw_user_meta_data ->> 'username'), ''), split_part(coalesce(new.email, 'usuario'), '@', 1), 'usuario'), 24)
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Timestamp automático para alterações.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at before update on public.posts for each row execute procedure public.set_updated_at();
drop trigger if exists comments_set_updated_at on public.comments;
create trigger comments_set_updated_at before update on public.comments for each row execute procedure public.set_updated_at();

-- Função central de autorização administrativa.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- Validação pública de disponibilidade do nome (a UNIQUE continua sendo a proteção definitiva).
create or replace function public.username_available(candidate text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select not exists (
    select 1 from public.profiles
    where lower(trim(username)) = lower(trim(candidate))
  );
$$;
revoke all on function public.username_available(text) from public;
grant execute on function public.username_available(text) to anon, authenticated;

-- Nunca permite que um usuário comum altere role; admins podem alterar outros usuários.
create or replace function public.protect_profile_role()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.role is distinct from old.role and auth.uid() is not null then
    if auth.uid() = old.id then
      raise exception 'Sua própria função não pode ser alterada por esta interface.';
    end if;
    if not public.is_admin() then
      raise exception 'Somente administradores podem alterar funções.';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists profiles_protect_role on public.profiles;
create trigger profiles_protect_role before update on public.profiles for each row execute procedure public.protect_profile_role();

-- ======================= RLS =======================
alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.reactions enable row level security;
alter table public.comments enable row level security;

-- PERFIS: nomes são públicos; cada usuário pode alterar apenas seus campos editáveis.
drop policy if exists "profiles_public_read" on public.profiles;
create policy "profiles_public_read" on public.profiles for select to anon, authenticated using (true);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "profiles_admin_update" on public.profiles;
create policy "profiles_admin_update" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- POSTS: público só lê publicados; admin controla tudo.
drop policy if exists "posts_public_read" on public.posts;
create policy "posts_public_read" on public.posts for select to anon, authenticated using (published = true or public.is_admin());
drop policy if exists "posts_admin_insert" on public.posts;
create policy "posts_admin_insert" on public.posts for insert to authenticated with check (public.is_admin());
drop policy if exists "posts_admin_update" on public.posts;
create policy "posts_admin_update" on public.posts for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "posts_admin_delete" on public.posts;
create policy "posts_admin_delete" on public.posts for delete to authenticated using (public.is_admin());

-- REAÇÕES: todos leem contagens; usuário autenticado controla apenas a própria reação.
drop policy if exists "reactions_public_read" on public.reactions;
create policy "reactions_public_read" on public.reactions for select to anon, authenticated using (true);
drop policy if exists "reactions_insert_own" on public.reactions;
create policy "reactions_insert_own" on public.reactions for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "reactions_update_own" on public.reactions;
create policy "reactions_update_own" on public.reactions for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "reactions_delete_own" on public.reactions;
create policy "reactions_delete_own" on public.reactions for delete to authenticated using (auth.uid() = user_id);

-- COMENTÁRIOS: leitura pública; autor cria/apaga o próprio; admin pode moderar.
drop policy if exists "comments_public_read" on public.comments;
create policy "comments_public_read" on public.comments for select to anon, authenticated using (true);
drop policy if exists "comments_insert_own" on public.comments;
create policy "comments_insert_own" on public.comments for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "comments_update_own" on public.comments;
create policy "comments_update_own" on public.comments for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "comments_delete_own_or_admin" on public.comments;
create policy "comments_delete_own_or_admin" on public.comments for delete to authenticated using (auth.uid() = user_id or public.is_admin());

-- Privilégios mínimos da API.
revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to anon, authenticated;
grant update (username, avatar_url, role) on public.profiles to authenticated;

grant select on public.posts to anon, authenticated;
grant insert, update, delete on public.posts to authenticated;
grant select on public.reactions to anon, authenticated;
grant insert, update, delete on public.reactions to authenticated;
grant select on public.comments to anon, authenticated;
grant insert, delete on public.comments to authenticated;
grant update (content) on public.comments to authenticated;
grant usage, select on sequence public.comments_id_seq to authenticated;

-- ======================= CONTEÚDO INICIAL =======================
insert into public.posts (slug,title,category,author,summary,content,score,icon,cover,featured,published,published_at)
values
('nerf-2kk-40kk','Pokémon de 2kk recebe nerf porque estava forte demais. O de 40kk segue normal.','Balanceamento','Redação Lógicas PXG','A equipe editorial tentou entender o critério. O critério pediu demissão.','Em mais um capítulo da série “balanceamento é uma ciência exata”, um Pokémon acessível recebeu ajustes após demonstrar a capacidade perigosa de funcionar bem nas mãos dos jogadores.\n\nEnquanto isso, opções várias vezes mais caras seguem circulando normalmente, protegidas pela tradicional regra econômica de que, se custou caro, provavelmente está tudo certo.\n\nNossa equipe tentou localizar a planilha usada para calcular o balanceamento. Fontes afirmam que ela existe, mas ninguém conseguiu confirmar se as fórmulas estão habilitadas.',88,'⚖️','red',false,true,'2026-08-13 12:00:00+00'),
('craft-73-itens','Novo craft exige 73 itens diferentes. Organização de backpack vira conteúdo endgame.','Craft','Departamento de Logística','Inventário cheio agora é mecânica de progressão e não um problema de design.','O novo craft chegou com uma proposta inovadora: transformar cada jogador em auxiliar de almoxarifado.\n\nPara concluir a receita, aventureiros devem reunir materiais de diferentes regiões, faixas de level e estados emocionais, além de descobrir em qual das 48 backpacks deixaram aquele item coletado três semanas atrás.\n\nA recomendação editorial é simples: crie uma planilha. Caso ela também fique complexa demais, parabéns, você desbloqueou o verdadeiro endgame.',79,'🔨','yellow',false,true,'2026-08-12 12:00:00+00'),
('farm-escala-6x1','Farm reduzido para melhorar a economia. Jogadores agora cumprem escala 6x1 no game.','Economia','Economia & Sofrimento','Especialistas confirmam que o melhor método de farm continua sendo ter tempo livre.','Com o objetivo declarado de preservar a economia, métodos de farm foram reduzidos e a comunidade imediatamente descobriu uma nova estratégia: jogar mais horas para ganhar a mesma coisa.\n\nAnalistas independentes classificaram a medida como um avanço importante na aproximação entre MMORPG e mercado de trabalho.\n\nAté o fechamento desta matéria, nenhuma carteira de trabalho havia sido assinada dentro do jogo.',91,'💰','blue',false,true,'2026-08-11 12:00:00+00'),
('evento-48h-segunda','Evento de 48 horas começa segunda-feira às 10h. Desempregados comemoram vantagem competitiva.','Eventos','Plantão de Eventos','Quem trabalha poderá participar integralmente através do poder da imaginação.','Um evento limitado de 48 horas foi anunciado para começar em pleno horário comercial, promovendo uma experiência imersiva baseada em escolhas difíceis.\n\nEntre trabalhar, estudar, dormir e concluir todas as etapas do evento, jogadores poderão selecionar até uma dessas atividades por vez.\n\nPara os demais, resta a tradicional modalidade competitiva conhecida como “ver os outros pegando recompensa no Discord”.',83,'🎉','purple',false,true,'2026-08-10 12:00:00+00'),
('drop-00011','Chance aumenta de 0,001% para 0,0011%. Servidores entram em clima de comemoração.','Drops','Instituto Brasileiro do RNG','Matemáticos foram acionados para confirmar se a diferença existe.','Após pedidos da comunidade, a chance de um item raro foi aumentada de 0,001% para 0,0011%, mudança descrita por especialistas como “tecnicamente um número maior”.\n\nJogadores veteranos já relatam os efeitos do buff: depois de milhares de tentativas, continuam sem o item, porém agora com uma esperança estatisticamente superior.\n\nO Lógicas PXG recomenda comemorar com moderação para não gastar toda a sorte antes do próximo respawn.',96,'✨','green',true,true,'2026-08-09 12:00:00+00'),
('item-a-item-b','Você precisa do item B para conseguir o item A. O item B precisa do item A.','PXG sendo PXG','Núcleo de Paradoxos','A solução oficial é simples: tenha conseguido antes de precisar.','Investigadores encontraram uma cadeia de progressão tão eficiente que consegue impedir a própria progressão.\n\nO item A depende do item B. O item B, demonstrando forte espírito de equipe, depende do item A.\n\nApós extensa análise, concluímos que o sistema funciona perfeitamente desde que você já tenha terminado antes de começar.',100,'🌀','dark',false,true,'2026-08-08 12:00:00+00')
on conflict (slug) do nothing;

-- ============================================================
-- DEPOIS DE CRIAR A SUA CONTA PELO SITE, torne-a admin assim:
-- update public.profiles set role = 'admin' where id = (
--   select id from auth.users where email = 'SEU_EMAIL_AQUI'
-- );
-- ============================================================


-- ======================= STORAGE DE CAPAS =======================

-- Bucket público para capas das matérias.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'post-images',
  'post-images',
  true,
  8388608,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Leitura pública das capas.
drop policy if exists "post_images_public_read" on storage.objects;
create policy "post_images_public_read"
on storage.objects for select
to public
using (bucket_id = 'post-images');

-- Somente administradores podem enviar/alterar/excluir capas.
drop policy if exists "post_images_admin_insert" on storage.objects;
create policy "post_images_admin_insert"
on storage.objects for insert
to authenticated
with check (bucket_id = 'post-images' and public.is_admin());

drop policy if exists "post_images_admin_update" on storage.objects;
create policy "post_images_admin_update"
on storage.objects for update
to authenticated
using (bucket_id = 'post-images' and public.is_admin())
with check (bucket_id = 'post-images' and public.is_admin());

drop policy if exists "post_images_admin_delete" on storage.objects;
create policy "post_images_admin_delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'post-images' and public.is_admin());
