-- Lógicas PXG V4.0 — audiência anônima e painel de acessos
-- Execute uma única vez no SQL Editor do Supabase.

create table if not exists public.access_events (
  id bigint generated by default as identity primary key,
  visitor_hash text not null check (visitor_hash ~ '^[a-f0-9]{64}$'),
  path text not null check (char_length(path) between 1 and 180),
  source text not null check (source in ('Direto','Google','Redes sociais','Outros')),
  viewed_at timestamptz not null default now()
);

create index if not exists access_events_viewed_at_idx on public.access_events (viewed_at desc);
create index if not exists access_events_visitor_date_idx on public.access_events (visitor_hash, viewed_at desc);

alter table public.access_events enable row level security;

drop policy if exists "access_events_admin_read" on public.access_events;
create policy "access_events_admin_read"
on public.access_events for select
to authenticated
using ((select public.is_admin()));

revoke all on public.access_events from anon, authenticated;
grant select on public.access_events to authenticated;

-- Endpoint público estritamente limitado: valida os campos e não aceita IP,
-- nome, e-mail, user-agent ou qualquer outro dado pessoal.
create or replace function public.record_access_event(
  p_visitor_hash text,
  p_path text,
  p_source text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_visitor_hash !~ '^[a-f0-9]{64}$'
     or char_length(p_path) not between 1 and 180
     or p_source not in ('Direto','Google','Redes sociais','Outros') then
    raise exception 'invalid access event';
  end if;

  -- Evita duplicações causadas por duplo clique ou recarregamento imediato.
  if exists (
    select 1 from public.access_events
    where visitor_hash = p_visitor_hash
      and path = p_path
      and viewed_at > now() - interval '3 seconds'
  ) then
    return;
  end if;

  insert into public.access_events (visitor_hash, path, source)
  values (p_visitor_hash, p_path, p_source);
end;
$$;

revoke all on function public.record_access_event(text,text,text) from public;
grant execute on function public.record_access_event(text,text,text) to anon, authenticated;

create or replace function public.admin_access_analytics(p_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  result jsonb;
  safe_days integer := greatest(1, least(coalesce(p_days, 30), 365));
  today_brt date := (timezone('America/Sao_Paulo', now()))::date;
begin
  if not (select public.is_admin()) then
    raise exception 'admin access required' using errcode = '42501';
  end if;

  with filtered as (
    select visitor_hash, source, (timezone('America/Sao_Paulo', viewed_at))::date as day
    from public.access_events
    where viewed_at >= ((today_brt - safe_days + 1)::timestamp at time zone 'America/Sao_Paulo')
  ),
  calendar as (
    select generate_series(today_brt - safe_days + 1, today_brt, interval '1 day')::date as day
  ),
  daily as (
    select c.day, count(f.*)::integer as views, count(distinct f.visitor_hash)::integer as visitors
    from calendar c left join filtered f on f.day = c.day
    group by c.day order by c.day
  ),
  sources as (
    select source, count(*)::integer as views
    from filtered group by source order by count(*) desc
  )
  select jsonb_build_object(
    'visitors_today', (select count(distinct visitor_hash) from filtered where day = today_brt),
    'views_today', (select count(*) from filtered where day = today_brt),
    'unique_visitors', (select count(distinct visitor_hash) from filtered),
    'daily_average', (select round(coalesce(sum(views),0)::numeric / safe_days) from daily),
    'daily', coalesce((select jsonb_agg(jsonb_build_object('day',day,'views',views,'visitors',visitors) order by day) from daily),'[]'::jsonb),
    'sources', coalesce((select jsonb_agg(jsonb_build_object('source',source,'views',views) order by views desc) from sources),'[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on function public.admin_access_analytics(integer) from public;
grant execute on function public.admin_access_analytics(integer) to authenticated;

comment on table public.access_events is 'Eventos anônimos usados exclusivamente para estatísticas de audiência.';
