-- Lógicas PXG V3.8 — gestão protegida de perfis e auditoria
create table if not exists public.admin_profile_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_username text not null,
  target_id uuid references public.profiles(id) on delete set null,
  target_username text not null,
  changes jsonb not null check (jsonb_typeof(changes) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists idx_admin_profile_audit_target_created
on public.admin_profile_audit(target_id, created_at desc);

create index if not exists idx_admin_profile_audit_actor_created
on public.admin_profile_audit(actor_id, created_at desc);

alter table public.admin_profile_audit enable row level security;

drop policy if exists "admin_profile_audit_admin_read" on public.admin_profile_audit;
create policy "admin_profile_audit_admin_read"
on public.admin_profile_audit for select to authenticated
using ((select public.is_admin()));

revoke all on public.admin_profile_audit from anon, authenticated;
grant select on public.admin_profile_audit to authenticated;

-- Edições administrativas deixam de ser aceitas diretamente pelo navegador.
-- A Edge Function valida a senha e grava com a chave secreta do servidor.
drop policy if exists "profiles_admin_update" on public.profiles;


